"""empty message

Revision ID: 8a66ba8e42b6
Revises: 5a8ae7f260ab
Create Date: 2022-11-27 15:58:01.358391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a66ba8e42b6'
down_revision = '5a8ae7f260ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
